// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
/*
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuC428DDsDhQ97SkJmuWZPd6--dz-sZ_o',
    appId: '1:904485738566:web:5fc89e98db2c2af1029247',
    messagingSenderId: '904485738566',
    projectId: 'mypet-609af',
    authDomain: 'mypet-609af.firebaseapp.com',
    storageBucket: 'mypet-609af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_0P1K3QpI2xh8HjuMCAOR23L-3L5Bk_8',
    appId: '1:904485738566:android:ac60a34e80522adb029247',
    messagingSenderId: '904485738566',
    projectId: 'mypet-609af',
    storageBucket: 'mypet-609af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4AFk-8WEipkz01j6RqIncwGb_GbNuyHY',
    appId: '1:904485738566:ios:ddbfe757798c5336029247',
    messagingSenderId: '904485738566',
    projectId: 'mypet-609af',
    storageBucket: 'mypet-609af.appspot.com',
    iosBundleId: 'com.example.myPet',
  );
}
*/